acme:
  email: me@example.com

metrics-server:
  args:
    - --logtostderr
    # On DigitalOcean the default DNS resolving fails, and the certificate
    # is not signed with the IP in the SAN (for good reason). As such, we
    # have to switch to InternalIP and allow insecure TLS.
    # See https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/150
    - --kubelet-preferred-address-types=InternalIP
    - --kubelet-insecure-tls

nginx-ingress:
  controller:
    kind: Deployment
    replicaCount: 2

    config:
      use-proxy-protocol: "true"

    service:
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
      omitClusterIP: true
      nodePorts:
        http: 32080
        https: 32443
    stats:
      service:
        omitClusterIP: true
    metrics:
      service:
        omitClusterIP: true

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx-ingress
            topologyKey: kubernetes.io/hostname
