trigger:
- master
pr:
  - master

jobs:
- job: BuildImage
  displayName: 'Build image'
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  # Only update the BuildNumber on 'master' (and not on a Pull Request)
  - script: |
      set -e
      VERSION=$(git describe --tags)
      echo "${VERSION}"
      echo "##vso[build.updatebuildnumber]${VERSION}"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'Use "git describe" as BuildNumber'

  - task: Docker@1
    displayName: 'Build image'
    inputs:
      dockerFile: Dockerfile
      imageName: 'openttd/iac:$(Build.BuildNumber)'
      addDefaultLabels: false

  # Only publish when it triggered on 'master' (and not on a Pull Request)
  - task: Docker@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'Publish image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'OpenTTD Docker Hub'
      command: 'Push an image'
      imageName: 'openttd/iac:$(Build.BuildNumber)'

  - task: Docker@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'Tag as bootstrap image'
    inputs:
      command: 'Tag image'
      arguments: 'openttd/iac:bootstrap'
      imageName: 'openttd/iac:$(Build.BuildNumber)'

  - task: Docker@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'Publish bootstrap image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'OpenTTD Docker Hub'
      command: 'Push an image'
      imageName: 'openttd/iac:bootstrap'
