apiVersion: v1
appVersion: staging
description: Binaries Proxy for OpenTTD
home: https://github.com/TrueBrain/OpenTTD-IaC
name: openttd-binaries-proxy
sources:
  - https://github.com/TrueBrain/OpenTTD-binaries-proxy
version: 0.1.0
