replicaCount: 1

image:
  repository: openttd/binaries-proxy

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  hosts:
    - proxy.binaries
  annotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
