replicaCount: 1

image:
  repository: openttd/dorpsgek

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  hosts:
    - dorpsgek
  annotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
