# DigitalOcean doesn't support proxy-protocol on its LoadBalancer.
# Also, it does not support IPv6.
# To solve this, we run our own IPv6 "LoadBalancer". But because DO doesn't
# support proxy-protocol, it is impossible to see which is IPv4 and which
# is IPv6. This we do need to know, to separate binary downloads, as the DO
# CDN also doesn't support IPv6.
# To work around this issue, we setup a second nginx-ingress (which reads
# exactly the same content as the one from openttd-base), but it does use
# proxy-protocol. Now we can see if requests are IPv4 (they come from a
# single IPv4, the LoadBalancer) or IPv6 (via proxy-protocol they are extended
# to their original IPv6).
# Hopefully soon DO supports proxy-protocol (or IPv6) on their LoadBalancer.

nginx-ingress:
  controller:
    kind: DaemonSet

    config:
      use-proxy-protocol: "true"

    service:
      type: NodePort
      nodePorts:
        http: 32080
        https: 32443
