# Create a 'deployer' ServiceAccount, who has full access in the global,
# production and staging namespace. This SA is used for the openttd-iac
# pod, so it can manager the full kubernetes from within.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: global

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployer-full-access
rules:
- apiGroups: ["", "extensions", "apps", "k8s.openttd.org"]
  resources: ["*"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployer-full-access
  namespace: global
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: global
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployer-full-access

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployer-full-access
  namespace: production
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: global
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployer-full-access

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployer-full-access
  namespace: staging
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: global
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployer-full-access
