ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/acme-http01-ingress-class: nginx
  domain: openttd.org
  enabled: true
