apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  s3.conf: |-
    @include kubernetes.conf

    <match **>
        @type s3
        @id out_s3
        @log_level info

        aws_key_id "#{ENV['AWS_KEY_ID']}"
        aws_sec_key "#{ENV['AWS_SEC_KEY']}"

        s3_bucket "#{ENV['S3_BUCKET']}"
        s3_region "#{ENV['S3_REGION']}"
        s3_endpoint "#{ENV['S3_ENDPOINT']}"

        s3_object_key_format "%{path}%Y/%m/%d/node-#{Socket.gethostname}-log-%{index}.%{file_extension}"

        <inject>
            time_key time
            tag_key tag
            localtime false
        </inject>
        <buffer>
            @type file
            path /var/log/fluentd-buffers/s3.buffer
            timekey 3600
            timekey_use_utc true
            chunk_limit_size 256m
        </buffer>
    </match>
